### ISSUE TITLE
Скриншоты вижу, а код где?

### ISSUE THREAD

**Issue by tshemsedinov** [YAGoOaR/Planes#1]

**Comment by YAGoOaR** [comment]
Добрый день! Я планирую сначала переделать участки кода, которые я писал более чем полгода назад, мне за них немного стыдно). Я отправлю сюда код через 1-3 дня.

**Comment by tshemsedinov** [comment]
Лучше всего коммитить как есть и прямо в репе рефакторить, это покажет, что ты растешь над собой с большой скоростью. Нечего кода стыдиться, но делай, как знаешь. Можешь немного подчистить и залить, а остальное рефакторить уже тут.

**Comment by YAGoOaR** [comment]
Хорошо! Тогда я сначала всё это через линтер прогоню и выложу сегодня-завтра.

**Comment by YAGoOaR** [comment]
Код добавил, буду рефакторить и работать над проектом каждый день
